repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        files: ^(src/|tests/|dags/)

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^(src/|tests/|dags/)

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: ./run_pylint.sh
        language: script
        types: [python]
        require_serial: true
        files: ^(src/|tests/|dags/)

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: bash -c 'PYTHONPATH=.:src ./.venv/bin/pytest tests'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        files: ^tests/
